name: Favorites anime and currently watching

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run script plugin
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.anilist.svg
        token: NOT_NEEDED
        base: ""
        plugin_anilist: yes
        plugin_anilist_medias: anime
        plugin_anilist_sections: favorites, watching
        plugin_anilist_limit: 1
        plugin_anilist_user: isolcat
